name: Sync Notion to JSON

on:
  schedule:
    - cron: "0 * * * *"  # Hourly
  workflow_dispatch:
  push:
    paths:
      - ".github/workflows/sync_notion.yml"
      - "sync_notation_to_json.py"
      - "requirements.txt"

env:
  PYTHON_VERSION: "3.10"

jobs:
  sync-notion:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # Needed to allow pushing back to the repo

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python ${{ env.PYTHON_VERSION }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run sync script
        env:
          NOTION_TOKEN: ${{ secrets.NOTION_TOKEN }}
          NOTION_DATABASE_ID: ${{ secrets.NOTION_DATABASE_ID }}
        run: python sync_notion_to_json.py

      - name: Commit and push changes
        uses: EndBug/add-and-commit@v9
        with:
          default_author: github_actions
          message: "chore: Auto-sync from Notion"
          add: "mindmap_data_synced.json"
          pull_strategy: pull
