name: Sync Notion to JSON

on:
  schedule:
    - cron: "*/5 * * * *"  # every 5 minutes
  workflow_dispatch:
  push:
    paths:
      - ".github/workflows/sync_notion.yml"
      - "sync_notation_to_json.py"

env:
  PYTHON_VERSION: "3.10"

jobs:
  sync-notion:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      actions: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python ${{ env.PYTHON_VERSION }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run sync script
        env:
          NOTION_TOKEN: ${{ secrets.NOTION_TOKEN }}
          NOTION_DATABASE_ID: ${{ secrets.NOTION_DATABASE_ID }}
        run: python sync_notation_to_json.py

      - name: Commit synced file (before pulling)
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"
          git add mindmap_data_synced.json
          git commit -m "temp: commit before rebase" || echo "Nothing to commit"

      - name: Pull latest changes
        run: git pull origin main --rebase

      - name: Final push with updated data
        uses: EndBug/add-and-commit@v9
        with:
          default_author: github_actions
          message: "chore: Auto-sync from Notion"
          add: mindmap_data_synced.json
          push: true
          fetch: true

      - name: List output
        run: ls -al
