name: Sync Notion to JSON

on:
  push:
    paths:
      - ".github/workflows/sync_notion.yml"
  schedule:
    - cron: "0 * * * *"  # Runs every hour

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"

    - name: Install dependencies
  run: pip install notion-client python-dotenv requests
  
    - name: Run sync script
      env:
        NOTION_TOKEN: ${{ secrets.NOTION_TOKEN }}
      run: python sync_notation_to_json.py

    - name: Commit and push changes
      run: |
        git config user.name "github-actions"
        git config user.email "github-actions@github.com"
        git add mindmap_data.json
        git commit -m "Sync from Notion" || echo "No changes to commit"
        git push
