name: Sync Notion to JSON

on:
  schedule:
    - cron: "0 * * * *"  # Every hour at minute 0
  workflow_dispatch:     # Manual trigger

env:
  PYTHON_VERSION: "3.10"
  REQUIREMENTS_FILE: "requirements.txt"

jobs:
  sync-notion:
    name: Sync Notion Data
    runs-on: ubuntu-latest
    permissions:
      contents: write  # Required for committing changes

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python ${{ env.PYTHON_VERSION }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r ${{ env.REQUIREMENTS_FILE }}

      - name: Run sync script
        env:
          NOTION_TOKEN: ${{ secrets.NOTION_TOKEN }}
          NOTION_DATABASE_ID: ${{ secrets.NOTION_DATABASE_ID }}
        run: python sync_notion_to_json.py

      - name: Commit and push changes
        uses: EndBug/add-and-commit@v9
        with:
          author_name: "GitHub Actions"
          author_email: "actions@github.com"
          message: "chore: Auto-update mindmap data from Notion"
          add: "mindmap_data_synced.json"
          pull_strategy: rebase
